### ISSUE TITLE
Breaks on external @import

### ISSUE THREAD

**Issue by michaelowens** [windicss/windicss#199]
**Describe the bug**
When using external imports (e.g. Google Fonts) it seems like windi doesn't parse the url properly. I think it might see it as a comment due to `//` in the url.

**Minimal Reproductions**
A clean vite/vue/windi set up is enough. I only added a style.css with an `@import` to a google font:
https://github.com/michaelowens/windi-import-bug

**Versions**
- vite-plugin-windicss: 0.10.2
- vite: 2.1.2
- framework(vue/react/svelte/etc): vue

**Additonal Context**
Here you can see it seems to cut off the url:

![image](https://user-images.githubusercontent.com/647632/112668599-fe553880-8e5e-11eb-8a18-fcbd9a382fd4.png)

**Comment by antfu** [comment]
Fixed with #191

**Comment by michaelowens** [comment]
I have updated to 2.5.6 and the issue persists. I've updated the git repo to use 2.5.6 where the issue can still be reproduced. @antfu

**Comment by michaelowens** [comment]
I see a test was added and it seems to pass successfully, yet after updating the issue still persists in the repo above after updating to 2.5.7.

**Comment by schelmo** [comment]
i think vite-plugin-windicss needs to be updated. windicss is included in the build of @windicss/plugin-utils and still is on 2.5.5

**Comment by antfu** [comment]
Confirmed we have some externalizing issue in the vite plugin, which should be fixed now. Can you try with `v0.10.3`? Thanks

**Comment by michaelowens** [comment]
Just confirmed it works :tada: Thanks!

**Comment by sooxt98** [comment]
I'm looking for this too XD, i thought something wrong with postcss; fixed by upgrading @windicss/plugin-utils
