### ISSUE TITLE
 Windi classes stop working if project has component with @abc="xyz()"

### ISSUE THREAD

**Issue by xorik** [windicss/windicss#325]
**Describe the bug**

Hi!

After updating from windicss 3.1.1 to 3.1.2 half of windi classes get broken. 

Windi classes get broken if template contains something like `@abc="xyz()"` or `@click="play()"`.
It can be also in a comment .e.g. `<!-- @click="play(i)" -->`

**Minimal Reproductions**

https://github.com/xorik/vite-tailwind-bug

Expected:
<img width="567" alt="Screen Shot 2021-06-07 at 22 42 32" src="https://user-images.githubusercontent.com/347044/121085114-c1ec7400-c7e1-11eb-9e27-5887e6257c05.png">

Actual:
<img width="263" alt="Screen Shot 2021-06-07 at 22 41 42" src="https://user-images.githubusercontent.com/347044/121085128-c749be80-c7e1-11eb-86c6-80b4f81fabdd.png">

If the issue is related to vite plugin, I can reopen the issue:
https://github.com/windicss/vite-plugin-windicss/issues/191

**Comment by voorjaar** [comment]
sorry. I made some mistake. should fixed in v3.1.3

**Comment by xorik** [comment]
@voorjaar No problem!
But it's still broken in the same test repo after update to 3.1.3: https://github.com/xorik/vite-tailwind-bug 😞

**Comment by voorjaar** [comment]
ok. After my test, the problem lies in the vite plugin. it seems classes not been passed to windi.

```
index.htmlen icon viewport xyz() <div <script virtual:windi.css
```
