### ISSUE TITLE
Incorrect CSS order for plugin components and utilities

### ISSUE THREAD

**Issue by saadeghi** [windicss/windicss#345]
Hi, Thanks for the awesome work.  
I think there is a problem with order of CSS styles that come from plugins.
I created a repo to reproduce this issue: https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue

There's a Tailwind CLI setup and Windi CLI setup. 
Both are using the [daisyUI plugin](https://github.com/saadeghi/daisyui) and both are generating style for the same HTML.
[Tailwind result file](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue/blob/master/dist/tailwind.css) is good and all rules have correct order.  
But [Windi result file](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue/blob/master/dist/windi.css) has CSS rules with wrong order.

For example in Tailwind file, [.btn-lg](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue/blob/ca21c5d63e509e110db0104805320d20a6e65b2a/dist/tailwind.css#L1478) comes **after** [.btn](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue/blob/ca21c5d63e509e110db0104805320d20a6e65b2a/dist/tailwind.css#L1192) as it should,  
but in Windi file [.btn-lg](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue/blob/ca21c5d63e509e110db0104805320d20a6e65b2a/dist/windi.css#L2675) comes **before** [.btn](https://github.com/saadeghi/windi-vs-tailwind-daisyui-class-order-issue/blob/ca21c5d63e509e110db0104805320d20a6e65b2a/dist/windi.css#L2684) which is wrong.  
Since `.btn-lg` is a modifier class for `.btn` it should come after `.btn`

HTML:
```html
  <button class='btn'>btn</button>
  <button class='btn btn-primary btn-sm'>btn btn-primary btn-sm</button>
  <button class='btn btn-lg'>btn btn-lg</button>
```
Tailwind output:
![](https://user-images.githubusercontent.com/7342023/122116094-7289f180-ce3a-11eb-93e4-4c1dec92dbd7.png)

Windi output:
![Screen Shot 2021-06-16 at 12 30 52 am](https://user-images.githubusercontent.com/7342023/122116130-7f0e4a00-ce3a-11eb-9ef9-177eef7cac72.png)

**Comment by MartinMa** [comment]
I noticed the same thing today.

For me it looks like the **preflight** styles seem to come **after** the styles of the **forms plugin**. Which should be the other way round.

In dev tools it looks like this for a `textarea` element.
```css
button, input, textarea {
    font-family: inherit;
    font-size: 100%;
    line-height: 1.15;
    margin: 0;
    padding: 0;
    line-height: inherit;
    color: inherit;
}
[type='text'], [type='email'], [type='url'], [type='password'], [type='number'], [type='date'], [type='datetime-local'], [type='month'], [type='search'], [type='tel'], [type='time'], [type='week'], [multiple], textarea, select {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    background-color: #fff;
    border-color: #6b7280;
    border-width: 1px;
    border-radius: 0px;
    padding-top: 0.5rem;
    padding-right: 0.75rem;
    padding-bottom: 0.5rem;
    padding-left: 0.75rem;
    font-size: 1rem;
    line-height: 1.5rem;
}
```

The problem here is that `padding: 0;` overwrites the forms plugin padding.

**Comment by cnb-philip** [comment]
Don't make me choose between Windi and Daisy :(

**Comment by kro-dev** [comment]
This is a show stopper for me now, as tailwindcss-fluid doesn't work either due to css styles being in the wrong order.  I'm switching back to Tailwind JIT for now. I hope this gets fixed.

**Comment by itpropro** [comment]
I had the same problem with textarea today, as the preflight.css seems to take precedence over the forms plugin.

**Comment by offlinehacker** [comment]
I noticed the same issue today. For some reason the order changed and no dependencies changed. I was just trying to extend windi theme, but now even after I reverted config, the issue persists. I am unsure if there is something cached or what is causing this nondeterministic behavior.

**Comment by offlinehacker** [comment]
We really do not want to switch to tailwindcss, so any ideas what is causing this issue or what to do for workaround or to fix would be appreciated.

@voorjaar @antfu

**Comment by antfu** [comment]
Should be fixed in v3.1.7

**Comment by pkrogel-kws** [comment]
@offlinehacker @itpropro @MartinMa 
 did v3.1.7 fix the issues for you? I’m still seeing the same problems.

**Comment by offlinehacker** [comment]
I can confirm it works now with version 3.1.7. Thank you very much for fixing this issue so fast 🍺

**Comment by dioxine** [comment]
hovers aren't working.
